apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      name: minio
  template:
    metadata:
      labels:
        name: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          args:
            - "server"
            - "/data"
          ports:
            - containerPort: 9000
          env:
            - name: MINIO_ROOT_USER
              value: {{ .Values.s3_user }}
            - name: MINIO_ROOT_PASSWORD
              value: {{ .Values.s3_pass }}
