apiVersion: apps/v1
kind: Deployment
metadata:
  name: EXAMPLE
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      name: EXAMPLE
  template:
    metadata:
      labels:
        name: EXAMPLE
    spec:
      containers:
        - name: EXAMPLE
          image: EXAMPLE:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
            - containerPort: 9091
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9091
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: 9091
            initialDelaySeconds: 5
            periodSeconds: 10
