apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: EXAMPLE
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: EXAMPLE
                port:
                  number: 3000
