apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      name: api-gateway
  template:
    metadata:
      labels:
        name: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: {{ .Values.registry }}api-gateway:latest
          ports:
            - containerPort: 3000
          env:
            - name: RATE_LIMITER_REDIS_HOST
              value: "rate-limiter-redis"
            - name: RATE_LIMITER_REDIS_PASSWORD
              value: "{{ index .Values "rate-limiter-redis" "auth" "password" }}"
