{{- range .Values.filters }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ . }}
  labels:
    app: {{ . }}
spec:
  selector:
    matchLabels:
      app: {{ . }}
  template:
    metadata:
      labels:
        app: {{ . }}
    spec:
      containers:
        - name: {{ . }}
          image: {{ $.Values.registry }}{{ . }}:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /mnt/nfs
              name: nfs-volume
      volumes:
        - name: nfs-volume
          nfs:
            path: /
            server: nfs
{{- end }}
