apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: localstripe
spec:
  rules:
    - http:
        paths:
          - path: /localstripe
            pathType: Prefix
            backend:
              service:
                name: localstripe
                port:
                  number: 8420
