apiVersion: apps/v1
kind: Deployment
metadata:
  name: projects-ms
  labels:
    app: projects-ms
spec:
  selector:
    matchLabels:
      app: projects-ms
  template:
    metadata:
      labels:
        app: projects-ms
    spec:
      containers:
        - name: projects-ms
          image: {{ .Values.registry }}projects-ms:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /mnt/nfs
              name: nfs-volume
      volumes:
        - name: nfs-volume
          nfs:
            path: /
            server: nfs
