apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-ms
  labels:
    app: users-ms
spec:
  selector:
    matchLabels:
      app: users-ms
  template:
    metadata:
      labels:
        app: users-ms
    spec:
      containers:
        - name: users-ms
          image: {{ .Values.registry }}users-ms:latest
          ports:
            - containerPort: 3000
          env:
            - name: AUTH_JWT_SECRET
              value: {{ .Values.auth_jwt_secret }}
            - name: REFRESH_JWT_SECRET
              value: {{ .Values.refresh_jwt_secret }}
