apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-ms
  labels:
    app: users-ms
spec:
  selector:
    matchLabels:
      app: users-ms
  template:
    metadata:
      labels:
        app: users-ms
    spec:
      containers:
        - name: users-ms
          image: TODO/users-ms:latest
          ports:
            - containerPort: 3000
