apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-gateway
spec:
  selector:
    matchLabels:
      name: ws-gateway
  template:
    metadata:
      labels:
        name: ws-gateway
    spec:
      containers:
        - name: ws-gateway
          image: {{ .Values.registry }}ws-gateway:latest
          ports:
            - containerPort: 3000
          env:
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq"
            - name: RABBITMQ_QUEUE
              value: "{{ .Values.filter_queue_name }}"
