apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-gateway
  labels:
    app: ws-gateway
spec:
  selector:
    matchLabels:
      app: ws-gateway
  template:
    metadata:
      labels:
        app: ws-gateway
    spec:
      containers:
        - name: ws-gateway
          image: localhost:5000/ws-gateway:latest
          ports:
            - containerPort: 3000
          env:
            - name: WS_ADAPTER_REDIS_HOST
              value: "ws_adapter_redis"
            - name: WS_ADAPTER_REDIS_PASSWORD
              value: "{{ .Values.ws_adapter_redis.auth.password }}"
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq"
            - name: RABBITMQ_QUEUE
              value: "{{ .Values.filter_queue_name }}"
