nameOverride: ""
fullnameOverride: ""

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

auth_jwt_secret: "secret"
filter_queue_name: "filters"

# Rate Limiter Redis
rate_limiter_redis:
  auth:
    enabled: yes
    password: "safePassword1"

# WS Adapter Redis
ws_adapter_redis:
  auth:
    enabled: yes
    password: "safePassword2"

# TODO mongo
