apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-gateway
spec:
  selector:
    matchLabels:
      name: ws-gateway
  template:
    metadata:
      labels:
        name: ws-gateway
    spec:
      containers:
        - name: ws-gateway
          image: ws-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: {{ $.Values.rabbitmq.service.ports.amqp | quote }}
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-auth-secret
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-auth-secret
                  key: password
            - name: RABBITMQ_QUEUE
              value: {{ .Values.filter_output_exchange }}
            - name: NOTIFICATION_QUEUE
              value: {{ .Values.notification_queue }}
            - name: WS_REDIS_HOST
              value: "ws-redis-master"
            - name: WS_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ws-redis-auth-secret
                  key: password
