apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ws-gateway
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # TODO
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-connection: "upgrade"
spec:
  rules:
    - http:
        paths:
          - path: /api/ws(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ws-gateway
                port:
                  number: 3000
