name: Deploy Picturas App

on:
  workflow_dispatch:

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Write production values to values-production.yaml
        run: |
          echo "${{ secrets.HELM_CONFIG_VALUES }}" > values-production.yaml

      - name: Deploy
        run: .github/scripts/deploy.sh
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
