name: Setup Kubernetes Cluster

on:
  workflow_dispatch:

jobs:
  setup-cluster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Connect via SSH and Setup Cluster
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Update and install prerequisites
            sudo apt-get update && sudo apt-get install -y \
              curl \
              apt-transport-https \
              ca-certificates \
              software-properties-common 
            
            # Install Docker
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository \
              "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu \
              $(lsb_release -cs) \
              stable"
            sudo apt-get update && sudo apt-get install -y docker-ce
            
            # Enable and start Docker
            sudo systemctl enable docker
            sudo systemctl start docker
            
            # Setup Docker Registry
            sudo docker run -d \
              --name registry \
              --restart=always \
              -p 5000:5000 \
              registry:2
            
            # Install kubeadm, kubelet, and kubectl
            sudo apt-get update && sudo apt-get install -y apt-transport-https curl
            sudo curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            sudo add-apt-repository \
              "deb https://apt.kubernetes.io/ kubernetes-xenial main"
            sudo apt-get update && sudo apt-get install -y kubelet kubeadm kubectl
            sudo apt-mark hold kubelet kubeadm kubectl
            
            # Initialize Kubernetes Cluster
            sudo kubeadm init --pod-network-cidr=192.168.0.0/16
            
            # Setup kubectl for the user
            mkdir -p $HOME/.kube
            sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
            sudo chown $(id -u):$(id -g) $HOME/.kube/config
            
            # Install Calico network plugin
            kubectl apply -f https://docs.projectcalico.org/v3.25/manifests/calico.yaml
            
            # Install Nginx Ingress Controller
            kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml
            
            echo "Cluster setup complete."
