name: Undeploy Picturas App

on:
  workflow_dispatch:

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Access Kubernetes Cluster
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          project_id: geometric-rock-440710-k5
          cluster_name: picturas-cluster
          location: europe-west2-a

      - name: Undeploy with helm
        run: |
          helm uninstall picturas
